-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.asset DROP CONSTRAINT IF EXISTS currency__fk;

ALTER TABLE IF EXISTS public.asset DROP CONSTRAINT IF EXISTS type_id__fk;

ALTER TABLE IF EXISTS public.asset DROP CONSTRAINT IF EXISTS user_id__fk;

ALTER TABLE IF EXISTS public.transaction DROP CONSTRAINT IF EXISTS currency__fk;

ALTER TABLE IF EXISTS public.transaction DROP CONSTRAINT IF EXISTS destination_asset__fk;

ALTER TABLE IF EXISTS public.transaction DROP CONSTRAINT IF EXISTS source_asset__fk;

ALTER TABLE IF EXISTS public.transaction DROP CONSTRAINT IF EXISTS type_id__fk;

ALTER TABLE IF EXISTS public.transaction DROP CONSTRAINT IF EXISTS user_id__fk;

ALTER TABLE IF EXISTS public."user" DROP CONSTRAINT IF EXISTS def_currency__fk;



DROP TABLE IF EXISTS public.asset;

CREATE TABLE IF NOT EXISTS public.asset
(
    id uuid NOT NULL,
    user_id integer,
    type_id integer,
    name character varying(50) COLLATE pg_catalog."default",
    balance numeric(10, 2),
    currency_id integer,
    description text COLLATE pg_catalog."default",
    CONSTRAINT asset_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.currency;

CREATE TABLE IF NOT EXISTS public.currency
(
    id serial NOT NULL,
    code character varying(3) COLLATE pg_catalog."default",
    symbol character varying(3) COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT currency_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transaction;

CREATE TABLE IF NOT EXISTS public.transaction
(
    id uuid NOT NULL,
    user_id integer,
    type integer,
    "timestamp" timestamp without time zone,
    source uuid,
    destination uuid,
    amount numeric(10, 2),
    currency_id integer,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transaction_type;

CREATE TABLE IF NOT EXISTS public.transaction_type
(
    id serial NOT NULL,
    description text COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT transaction_type_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."user";

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    login character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    default_currency integer,
    email character varying(50) COLLATE pg_catalog."default",
    registration_date timestamp without time zone NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT currency__fk FOREIGN KEY (currency_id)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT type_id__fk FOREIGN KEY (type_id)
    REFERENCES public.transaction_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT user_id__fk FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT currency__fk FOREIGN KEY (currency_id)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT destination_asset__fk FOREIGN KEY (destination)
    REFERENCES public.asset (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT source_asset__fk FOREIGN KEY (source)
    REFERENCES public.asset (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT type_id__fk FOREIGN KEY (type)
    REFERENCES public.transaction_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT user_id__fk FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT def_currency__fk FOREIGN KEY (default_currency)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;