-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asset
(
    id uuid NOT NULL,
    user_id integer,
    type_id integer,
    name character varying(50) COLLATE pg_catalog."default",
    balance numeric(10, 2),
    currency_id integer,
    description text COLLATE pg_catalog."default",
    CONSTRAINT asset_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.currency
(
    id integer NOT NULL,
    code character varying(3) COLLATE pg_catalog."default",
    symbol character varying(3) COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT currency_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id),
    CONSTRAINT role_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.transaction
(
    id uuid NOT NULL,
    user_id integer,
    type integer,
    "timestamp" timestamp without time zone,
    source uuid,
    destination uuid,
    amount numeric(10, 2),
    currency_id integer,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaction_type
(
    id serial NOT NULL,
    description text COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT transaction_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    login character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    default_currency integer,
    email character varying(50) COLLATE pg_catalog."default",
    registration_date timestamp without time zone NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT currency__fk FOREIGN KEY (currency_id)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT type_id__fk FOREIGN KEY (type_id)
    REFERENCES public.transaction_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.asset
    ADD CONSTRAINT user_id__fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT currency__fk FOREIGN KEY (currency_id)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT destination_asset__fk FOREIGN KEY (destination)
    REFERENCES public.asset (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT source_asset__fk FOREIGN KEY (source)
    REFERENCES public.asset (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT type_id__fk FOREIGN KEY (type)
    REFERENCES public.transaction_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT user_id__fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT def_currency__fk FOREIGN KEY (default_currency)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Insert basic roles
INSERT INTO "role" (name) VALUES 
    ('USER'),
    ('ADMIN');

-- Insert basic types
INSERT INTO asset_types (name, description) VALUES 
    ('Cash', 'Physical cash holdings'),
    ('Bank Account', 'Checking or savings accounts'),
    ('Credit Card', 'Credit card accounts'),
    ('Investment', 'Investment accounts, stocks, bonds'),
    ('Other', 'Other asset types');

-- Insert basic currencies
INSERT INTO currency (code, symbol, name) VALUES 
    ('EUR', '€', 'Euro'),
    ('USD', '$', 'US Dollar'),
    ('GBP', '£', 'British Pound');

-- Insert basic transaction types
INSERT INTO transaction_type (name, description) VALUES 
    ('Income', 'Money added to an account'),
    ('Expense', 'Money removed from an account'),
    ('Transfer', 'Money transferred between accounts');

END;